# Documentation: http://docs.travis-ci.com/user/languages/julia
language: julia
notifications:
  email: false
julia:
  - 1.6
  - nightly
os:
  - linux
  - osx
  - windows
arch:
  - x64
cache:
  directories:
    - ~/.julia/artifacts
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - travis_wait 45 julia --project --color=yes --check-bounds=yes -e 'using Pkg; Pkg.instantiate(); Pkg.build(; verbose = true); Pkg.test( ; coverage=true)';
jobs:
  fast_finish: true
  allow_failures:
    - julia: nightly
    - os: windows
codecov: true
coveralls: true