# Documentation: http://docs.travis-ci.com/user/languages/julia
language: julia
notifications:
  email: false
julia:
  - 1.6
  - nightly
os:
  - linux
  - osx
  - windows
arch:
  - x64
cache:
  directories:
    - ~/.julia/artifacts
script:
  - julia --color=yes -e "if VERSION < v\"0.7.0-DEV.5183\"; Pkg.clone(pwd()); Pkg.build(\"${JL_PKG}\"); else using Pkg; if VERSION >= v\"1.1.0-rc1\"; Pkg.build(verbose=true); else Pkg.build(); end; end"
  - julia --check-bounds=yes --color=yes -e "if VERSION < v\"0.7.0-DEV.5183\"; Pkg.test(\"${JL_PKG}\", coverage=true); else using Pkg; Pkg.test(coverage=true); end"
jobs:
  fast_finish: true
  allow_failures:
    - julia: nightly
    - os: windows
after_success:
  - |
    julia -e '
      using Pkg
      Pkg.add("Coverage")
      using Coverage
      Codecov.submit(process_folder())'
  - |
    julia -e '
      using Pkg
      Pkg.add("Coverage")
      using Coverage
      Coveralls.submit(process_folder())'