# Documentation: http://docs.travis-ci.com/user/languages/julia
language: julia
notifications:
  email: false
julia:
  - 1.6
  - nightly
os:
  - linux
  - osx
  - windows
arch:
  - x64
cache:
  directories:
    - ~/.julia/artifacts
script:
  - travis_wait 45 julia --color=yes -e "if VERSION < v\"0.7.0-DEV.5183\"; Pkg.clone(pwd()); Pkg.build(\"${JL_PKG}\"); else using Pkg; if VERSION >= v\"1.1.0-rc1\"; Pkg.build(verbose=true); else Pkg.build(); end; end"
jobs:
  fast_finish: true
  allow_failures:
    - julia: nightly
    - os: windows
codecov: true
coveralls: true